# Site settings
title: Jake Gavin
email: jakegavin@gmail.com
description: >
  Jake Gavin is a software developer at Planning Center Online in Seattle, WA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakegavin.net" # the base hostname & protocol for your site
twitter_username: jake_gavin
github_username:  jakegavin

# Build settings
markdown: kramdown
